name: 'insert_overwrite_demo'
version: '1.0.0'
config-version: 2

# Profile configuration
profile: 'databricks_insert_overwrite'

# Project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  insert_overwrite_demo:
    +materialized: table
    +file_format: delta
    # Disable contract enforcement to skip slow information_schema queries
    +contract:
      enforced: false

    # Staging models - base transformations
    staging:
      +materialized: view

    # Marts models - final analytics-ready tables
    marts:
      +materialized: incremental
      +on_schema_change: "fail"

      # Partitioned models use insert_overwrite
      partitioned:
        +incremental_strategy: insert_overwrite
        +partition_by: "order_date"

      # Liquid clustered models use insert_overwrite
      liquid_clustered:
        +incremental_strategy: insert_overwrite

# Seeds configuration
seeds:
  insert_overwrite_demo:
    +quote_columns: false

# Tests configuration
tests:
  insert_overwrite_demo:
    +store_failures: true

# Variables
vars:
  # ⚠️ IMPORTANT: Update these values for your environment!
  # These will be overridden by job parameters in Databricks jobs,
  # but are used for local dbt development and testing
  catalog: "main"           # Replace with your Unity Catalog name
  schema: "your_schema"     # Replace with your schema name
